### PR TITLE
Add script to generate services exposing Prisma

### PR DESCRIPTION
**Pull request by davidfou**
First of all, thanks for sharing your work. It saved me time to set up the same thing on my side!

I found it quite cumbersome to add one function each time I wanted to query some data with Prisma. I looked for a way to expose the Prisma methods so I can customize the calls directly on the Remix side.

My first attempt was to have a an abstract class looking like this:

```typescript
/* packages/prisma/src/BaseService.ts */
import { WorkerEntrypoint } from "cloudflare:workers";
import { PrismaClient, Prisma } from "@prisma/client";
import { PrismaD1 } from "@prisma/adapter-d1";


export interface Env {
  DB: D1Database,
}

interface IGenericService<T extends Prisma.ModelName> {
  findUnique: PrismaClient[Uncapitalize<T>]["findUnique"];
  // other Prisma methods...
}

export abstract class BaseService<T extends Prisma.ModelName>
  extends WorkerEntrypoint<Env>
  implements IGenericService<T>
{
  protected db: PrismaClient;

  constructor(...args: ConstructorParameters<typeof WorkerEntrypoint<Env>>) {
    super(...args);
    const adapter = new PrismaD1(this.env.DB);
    this.db = new PrismaClient({ adapter });
  }

  abstract get modelName(): Uncapitalize<T>;

  get findUnique() {
    return this.db[this.modelName].findUnique;
  }

  // other Prisma methods...
}

/* packages/prisma/src/index.ts */
import { BaseService } from "./BaseService";


export class UserService extends BaseService<"User"> {
  // Custom method
  fetchUsers() {
    return this.db.user.findMany();
  }
}

export default {
  // An error occurs when deploying this worker without register event handlers as default export.
  async fetch() {
    return new Response("Healthy!");
  },
};
```

The problem which I faced here is that TypeScript gets lost because it cannot determine the type when calling the method `findUnique` on the `UserService`. The only solution I found was a script to generate the classes for all the models.

Another issue I encountered (also with the current solution), is loosing some typing when wrapping the service with `Service` provided by Cloudflare dependency. It ensures only async functions are called on the Remix side, but it also interferes with Prisma (e.g. passing `{ select: { email: true } }` will return a type where all the field are selected).

I'd love to get your opinion on that topic and know if you faced such challenges.

### CODE REVIEW

**Comment by chimame** [comment]
hi @davidfou

Thank you for sharing your opinion. I understand the problem you have.
However, I don't have the solution you want. Please give me some time to think about it.

**Comment by chimame** [comment]
@davidfou 

Let me first write down what I think is a solution to your problem.
Prisma itself becomes a Cloudflare Worker, and the code to establish the interface as an RPC could be implemented as follows:

```ts
// prisma workers
import { WorkerEntrypoint } from "cloudflare:workers";
import { connection } from "./database/client";
import type { Prisma } from "@prisma/client";
import * as runtime from '@prisma/client/runtime/library.js';
import $Result = runtime.Types.Result

export interface Env {
  DB: D1Database,
}

export class UserService extends WorkerEntrypoint<Env> {
  findMany<T extends Prisma.UserFindManyArgs>(
    args?: Prisma.SelectSubset<T, Prisma.UserFindManyArgs>
  ): Prisma.PrismaPromise<$Result.GetResult<Prisma.$UserPayload, T, 'findMany'>> {
    const db = connection(this.env.DB)
    return db.user.findMany(args);
  }

  async test() {
    const fetchUsers = await this.findMany({select: {id: true}});
    // fetchUsers type is { id: number }[]
  }
}

export default {
  // An error occurs when deploying this worker without register event handlers as default export.
  async fetch() {
    return new Response("Healthy!");
  },
};
```

```ts
// remix
import type { LoaderFunctionArgs } from "@remix-run/cloudflare";

export const loader = async ({ context }: LoaderFunctionArgs) => {
  using users = await context.cloudflare.env.USER_SERVICE.findMany({select: {id: true}});
  // users type is not { id: number }[]

  return { users }
}
```

If you don't define the function using generics, you won't be able to achieve one of the challenges you think of - changing the return type depending on the arguments.
Surely you can achieve what you want by automatically generating this code for each model?

However, at the end, I wrote code to call Prisma Workers from Remix using Service Bindings, but it didn't seem to support generics.

**Comment by davidfou** [comment]
Thanks for having a look.

That's what the script I attached to this PR takes care for. It generates one class per model and it exposes all methods from Prisma.

Regarding loosing the type on the remix side, I fixed it with the following workaround:

```typescript
type PrismaMethods = {
  findUnique: unknown;
  findUniqueOrThrow: unknown;
  findFirst: unknown;
  findFirstOrThrow: unknown;
  findMany: unknown;
  create: unknown;
  update: unknown;
  upsert: unknown;
  delete: unknown;
  createMany: unknown;
  createManyAndReturn: unknown;
  updateMany: unknown;
  deleteMany: unknown;
  count: unknown;
  aggregate: unknown;
  groupBy: unknown;
};

export type CustomService<T extends WorkerEntrypoint & PrismaMethods> = Service<
  Omit<T, keyof PrismaMethods>
> &
  Pick<T, keyof PrismaMethods>;
  
interface Env {
  USER_SERVICE: CustomService<UserService>;
}
```

The `CustomService` type will expose the prisma methods as they are. That's not a problem given they are all async functions.

So far, I didn't face any issue and the code is strongly typed.

**Comment by chimame** [comment]
I also thought that the only way to support return types corresponding to arguments was to create a Service Bindings type on the Remix side. Thank you for creating the type.

If you don't mind, could you rewrite the code to use the Service Bindings generated by the PR generator and the above type? I think this would be a great use case.

I would love to merge your great ideas and code.

**Comment by davidfou** [comment]
Here it is! Let me know if there is still something you'd like to see different

**Review by chimame — APPROVED** [review]
Great!
I'll merge it right away.

I think this example will be easier to understand if you add something like the following to the `loader` function on the `/users/[:id]` page, so I'll add that later.

```ts
import type { LoaderFunctionArgs } from "@remix-run/cloudflare";

export const loader = async ({ context, params }: LoaderFunctionArgs) => {
  const { id } = params;
  const user = await context.cloudflare.env.USER_SERVICE.findUnique({ select: { id: true, name: true }, where: { id: Number(id) } });

  // user type is inferred as { id: number, name: string | null } | null
  return { user };
}
```

**Pull request merged**
